export {
  LAB_BASE,
  LAB_CHAPTER_IDS,
  LAB_INTERACTION_LABEL,
  LAB_LEARN,
  LAB_SAMPLE_LABEL,
  LAB_SLUG,
  LAB_STATUS,
  LAB_THESIS,
  LAB_TITLE,
  TRUTH_LABEL,
} from './types';
export type {
  AutomateArtifact,
  AutomateRun,
  CaseMark,
  ClauseMark,
  EdgeState,
  FieldStatus,
  HandoffArtifact,
  HandoffChoice,
  HumanDecision,
  JudgeArtifact,
  LabChapter,
  LabChapterId,
  LabProject,
  ObserveArtifact,
  PreserveArtifact,
  PublishArtifact,
  RelateArtifact,
  RelateClaim,
  StoryLayerId,
  StructureArtifact,
  StructureFieldKey,
  TruthKind,
} from './types';

export {
  LAB_CHAPTERS,
  getLabChapter,
  nextLabChapter,
  prevLabChapter,
} from './chapters';
export {
  DEPENDENCIES,
  FIELD_STATUSES,
  HANDOFF_CHOICES,
  HANDOFF_FALLBACK,
  JUDGE_CASES,
  JUDGE_CLAUSES,
  KEPT_HUMAN_OPTIONS,
  LOCAL_RULESET,
  OBSERVE_SAMPLE,
  PRESERVE_FALLBACKS,
  PROPOSED_CLAIM_SAMPLE,
  PUBLISH_AUDIENCES,
  PUBLISH_START_ORDER,
  RELATE_CLAIMS,
  SAMPLE_CARD,
  SAMPLE_RECORDS,
  SEEDED_AI_SUGGESTION,
  STORY_LAYERS,
  STRUCTURE_FIELDS,
  THIRTY_DAY_SAMPLE,
} from './sample';
export {
  automateNotes,
  handoffNotes,
  judgeNotes,
  observeReady,
  preserveNotes,
  projectToJson,
  projectToMarkdown,
  publishNotes,
  relateNotes,
  structureNotes,
} from './checks';
export { LAB_MARKS, LAB_MEDIA, labMark, labMedia } from './media';
export type { LabMarkAsset, LabMarkId, LabMediaAsset } from './media';
export {
  LAB_FORMATS,
  LAB_INSTRUCTOR,
  LAB_LENSES,
  LAB_NEXT,
  LAB_PREMISE,
  LAB_QUESTIONS,
  LAB_RHYTHM,
  LAB_SHARED_CENTER,
  LAB_TOOLS,
} from './proposal';
