/**
 * Presenter cue sheet — Learn AI Without Losing Yourself (~40 min).
 * Consumed only by the unlisted /rehearse page (noindex).
 */

export type LearnAiCueSegment =
  | 'opening'
  | 'writing'
  | 'research'
  | 'brainstorming'
  | 'synthetic_staff'
  | 'advanced_systems'
  | 'interpassivity'
  | 'what_stays_human'
  | 'closing'
  | 'flex'

export type LearnAiCueBeat = {
  id: string
  timeRange: string
  segment: LearnAiCueSegment
  slideLabel: string
  screenAction: string
  script: string
  altJoke?: string
  teachingGoal: string
  criticalTakeaway: string
  slideImageUrl?: string
  notes?: string
  /** Skill to say out loud on stage (edutainment). */
  skillWord?: string
  /** Big on-screen line (quote slide). */
  onScreenLine?: string
  /** One clarifying sentence after the quote slide. */
  onScreenGloss?: string
  /** Spoken bridge entering this beat (from the prior idea). */
  transitionFromPrior?: string
  /** Spoken bridge exiting this beat (handoff to the next). */
  transitionToNext?: string
  /** Optional culture / meme seasoning (not the same as altJoke). */
  cultureBeat?: string
  /** v2 deck: editorial intent for the slide visual. */
  slideVisualPurpose?: string
  /** Image-generation prompt — dark editorial direction. */
  slideImagePromptDark?: string
  /** Image-generation prompt — light-background variant. */
  slideImagePromptLight?: string
  /** Aligns this beat with `learn-ai-slide-prompts-v2` slide numbers. */
  deckSlideNumber?: number
}

export const LEARN_AI_CUE_SEGMENT_ORDER: readonly LearnAiCueSegment[] = [
  'opening',
  'writing',
  'research',
  'brainstorming',
  'synthetic_staff',
  'advanced_systems',
  'interpassivity',
  'what_stays_human',
  'closing',
  'flex',
] as const

export const LEARN_AI_CUE_SEGMENT_LABEL: Record<LearnAiCueSegment, string> = {
  opening: 'Opening (0:00–5:00)',
  writing: 'Segment 1 — Writing Without Sounding Possessed (5:00–10:00)',
  research: 'Segment 2 — Research Without Fake Mastery (10:00–18:00)',
  brainstorming: 'Segment 3 — Brainstorming Without Flattening Creativity (18:00–22:00)',
  synthetic_staff: 'Segment 4 — I Lost My Job and Gained 10 AI Assistants (22:00–27:00)',
  advanced_systems:
    'Advanced Systems — When Help Becomes Infrastructure (27:00–34:45; Interpassivity beat sits between automation and Part-time job)',
  interpassivity: 'Interpassivity — when the system performs the response for you (31:36–32:18 · deck slide 46)',
  what_stays_human: 'What Stays Human (34:42–37:42)',
  closing: 'Closing (37:42–40:42)',
  flex: 'Flex time / expansion',
}

export const LEARN_AI_CUE_SHEET_BEATS: readonly LearnAiCueBeat[] = [
  {
    id: 'opening-01',
    timeRange: '0:00–0:28',
    segment: 'opening',
    slideLabel: 'Title / hook',
    screenAction: 'Walk on; title up.',
    script: 'Quick question before we begin:\n\nHow many of you started using AI because you were curious?\n\nAnd how many of you started using it because you were already behind?\n\n[pause]',
    altJoke: 'How many of you got here through innovation, and how many through Outlook?',
    teachingGoal: 'Frame the room as tired and pressured.',
    criticalTakeaway: 'Most people arrived through overload, not futurism.',
  },
  {
    id: 'opening-02',
    timeRange: '0:28–0:52',
    segment: 'opening',
    slideLabel: 'That is the room',
    screenAction: 'Advance.',
    script: 'Yeah.\n\nThat is the room.\n\nNot the room of futurists.\nNot the room of people saying, "Finally, the future has arrived."\n\nThe room of people with too many emails, too many tabs, too many things to summarize, too many things to make sound better, and not enough time to be a full person while doing any of it.\n\n[pause for laugh]',
    altJoke: 'A lot of modern work is just sounding calm in writing while everything inside you is buffering.',
    teachingGoal: 'Recognition laugh.',
    criticalTakeaway: 'AI meets people already underwater.',
  },
  {
    id: 'opening-03',
    timeRange: '0:52–1:12',
    segment: 'opening',
    slideLabel: 'Why that matters',
    screenAction: 'Advance.',
    script: 'I think that matters.\n\nBecause most people did not arrive here through philosophy.\n\nThey arrived here through some version of:\n\n"I need help right now."',
    teachingGoal: 'Name the non-philosophical entry.',
    criticalTakeaway: 'Help-first adoption, not ideology.',
  },
  {
    id: 'opening-04',
    timeRange: '1:12–1:38',
    segment: 'opening',
    slideLabel: 'Help and judgment',
    screenAction: 'Advance.',
    script: 'And that is why AI is weird.\n\nBecause it really is helpful.\n\nBut it is also one of the only things I can think of that can help you while quietly making you feel judged by how much help you apparently need.\n\n[pause for laugh]',
    altJoke: 'The tool is useful, but the relationship is humiliating in a very efficient way.',
    teachingGoal: 'Humor through recognition.',
    criticalTakeaway: 'Help and exposure arrive together.',
  },
  {
    id: 'opening-05',
    timeRange: '1:38–2:02',
    segment: 'opening',
    slideLabel: 'Email joke',
    screenAction: 'Advance.',
    script: 'Like: great, thank you for helping me write this email.\n\nI did not realize I also needed help becoming the kind of person who sends emails like that.\n\n[pause]',
    teachingGoal: 'Concrete social shame beat.',
    criticalTakeaway: 'The tool reshapes who you sound like.',
  },
  {
    id: 'opening-06',
    timeRange: '2:02–2:28',
    segment: 'opening',
    slideLabel: 'Not neutral',
    screenAction: 'Advance.',
    script: 'These tools are not entering our lives in some neutral way.\n\nThey are arriving at the exact point where a lot of us are already thinking:\n\nI do not want to write this.\nI do not want to summarize this.\nI do not want to pretend I deeply understand this meeting.\nI do not want to brainstorm on command.\nI do not want to sound confused, rude, or replaceable.\nI just need to get through the day without embarrassing myself professionally.\n\n[pause for recognition]',
    teachingGoal: 'List the hidden refusals.',
    criticalTakeaway: 'AI lands on top of existing shame and fatigue.',
  },
  {
    id: 'opening-07',
    timeRange: '2:28–2:48',
    segment: 'opening',
    slideLabel: 'Machine offers help',
    screenAction: 'Advance.',
    script: 'And then the machine shows up like:\n\n"I can help with that."\n\n[pause]\n\nWhich is incredible.\n\nAnd also slightly insulting.',
    teachingGoal: 'Punch / contradiction.',
    criticalTakeaway: 'Relief and slight insult coexist.',
  },
  {
    id: 'opening-08',
    timeRange: '2:48–3:12',
    segment: 'opening',
    slideLabel: 'Confidence is changing',
    screenAction: 'Advance.',
    script: 'One of the things I have been noticing is that AI is not just changing how fast we work.\n\nIt is changing what confidence feels like.\n\n[pause]',
    altJoke: 'Confidence used to come from doing the work. Now it can also come from formatting.',
    teachingGoal: 'Bridge to synthetic confidence.',
    criticalTakeaway: 'Confidence shifts from earned to styled.',
  },
  {
    id: 'opening-09',
    timeRange: '3:12–3:36',
    segment: 'opening',
    slideLabel: 'Confidence used to mean',
    screenAction: 'Advance.',
    script: 'Because confidence used to mean something like:\n\nI studied. I practiced. I did the work. I know this well enough to stand behind it.\n\nIt was a relationship.\n\nYour boss feels confident you can do the task.\nYou feel confident going into the presentation.\nYou feel confident because you actually understand what you are saying.\n\n[pause]',
    teachingGoal: 'Define old confidence.',
    criticalTakeaway: 'Confidence was relational and earned.',
  },
  {
    id: 'opening-10',
    timeRange: '3:36–4:00',
    segment: 'opening',
    slideLabel: 'Tone before knowing',
    screenAction: 'Advance.',
    script: 'And now a machine can give you the tone of confidence, the shape of confidence, the formatting of confidence, the vibe of readiness — before you actually know.\n\n[pause]',
    teachingGoal: 'Memorable thesis line.',
    criticalTakeaway: 'Fluency can outrun comprehension.',
    onScreenLine: 'Generate the feeling of confidence faster than understanding.',
    onScreenGloss: 'Usefulness is not the same as ownership of the idea.',
  },
  {
    id: 'opening-11',
    timeRange: '4:00–4:22',
    segment: 'opening',
    slideLabel: 'Not abstract',
    screenAction: 'Let quote land; advance.',
    script: 'And that is not abstract.\n\nThat is every clean summary.\nEvery polished outline.\nEvery convincing paragraph you suddenly feel ready to repeat.',
    teachingGoal: 'Ground the abstraction.',
    criticalTakeaway: 'Synthetic confidence shows up in ordinary deliverables.',
  },
  {
    id: 'opening-12',
    timeRange: '4:22–4:42',
    segment: 'opening',
    slideLabel: 'Algorithmic intimacy',
    screenAction: 'Advance.',
    script: 'And meanwhile the systems around us are getting weirder in a very intimate way.\n\nAI cannot do my laundry yet.\n\nBut it can sort my bills, my emails, my notes, my reminders, my calendar — and at this point I am not fully convinced the algorithm does not know more about some of my patterns than I do.\n\n[pause for laugh]\n\nThe machine cannot fold my clothes.\n\nBut it can increasingly clean up after my cognition.',
    teachingGoal: 'Intimacy without embodiment.',
    criticalTakeaway: 'Systems organize and predict us, not just help.',
  },
  {
    id: 'opening-13',
    timeRange: '4:42–5:00',
    segment: 'opening',
    slideLabel: 'Speed + method',
    screenAction: 'Advance quickly through bullets if short on time.',
    script: 'Human talking to human. Human talking to AI. AI talking to AI.\n\nInformation now moves faster between machines than understanding moves between people.\nThe files are syncing. The humans are still buffering.\n\n[pause for laugh]\n\nTechnological acceleration is becoming traffic — robot cars, delivery bots — hard to opt out of.\n\nThis talk is the uncomfortable middle: help, speed, leverage — and flattening, dependence, false confidence, maintenance labor.\n\nTonight: pressure, prompt, problem, practice.\n\nUse AI for assistance, not surrender.\n\n[pause]',
    teachingGoal: 'Land method + title promise in one sprint.',
    criticalTakeaway: 'Stay awake inside usefulness; workshop rhythm is set.',
    skillWord: 'Prompting',
  },
  {
    id: 'writing-01',
    timeRange: '5:00–5:22',
    segment: 'writing',
    slideLabel: 'Bridge + hook',
    screenAction: 'Advance.',
    script: 'Let us start with one of the most dangerous social situations in modern life:\n\nwriting something professional.',
    teachingGoal: 'Segment hook.',
    criticalTakeaway: 'Professional writing is high-stakes performance.',
    skillWord: 'Prompting',
  },
  {
    id: 'writing-02',
    timeRange: '5:22–5:48',
    segment: 'writing',
    slideLabel: 'Where we hand ourselves over',
    screenAction: 'Advance.',
    script: 'Not writing a book.\n\nI mean an email, a Slack message, a follow-up — warm, clear, competent, strategic, emotionally stable — while you yourself are maybe not fully those things.\n\n[pause for laugh]\n\nThis is where AI feels less like innovation and more like emergency emotional formatting.',
    altJoke: 'AI is incredible at making you sound like someone who has slept.',
    teachingGoal: 'Relatable pressure.',
    criticalTakeaway: 'Tone work is vulnerability work.',
  },
  {
    id: 'writing-03',
    timeRange: '5:48–6:14',
    segment: 'writing',
    slideLabel: 'LinkedIn hostage',
    screenAction: 'Optional: show generic AI email on screen.',
    script: 'You type rough thoughts. The machine gives you back:\n\n"I hope this finds you well…"\n"I wanted to thoughtfully follow up…"\n"I remain enthusiastic about aligning on next steps…"\n\n[look up]\n\nThis sounds like LinkedIn wrote it during a hostage situation.\n\n[pause for laugh]\n\nOr worse: it sounds good enough.',
    altJoke: 'This is not warmth. This is strategic moisturization.',
    teachingGoal: 'Funny misuse.',
    criticalTakeaway: 'Acceptable polish can erase a person.',
  },
  {
    id: 'writing-04',
    timeRange: '6:14–6:42',
    segment: 'writing',
    slideLabel: 'Danger is acceptable',
    screenAction: 'Advance.',
    script: 'That is the danger.\n\nNot that it is terrible.\nThat it is acceptable.\n\nPolished, calm, competent, employable — but like absolutely nobody.\n\nIt removes all evidence that a person with stakes was ever involved.',
    teachingGoal: 'Name the moral hazard.',
    criticalTakeaway: 'Efficiency can replace sincerity.',
    skillWord: 'Tone',
  },
  {
    id: 'writing-05',
    timeRange: '6:42–7:08',
    segment: 'writing',
    slideLabel: 'Better method setup',
    screenAction: 'Advance.',
    script: 'So here is the better method.\n\nNot: "Write this for me."\n\nMore like: "Help me structure what I actually mean."\n\n[pause]',
    teachingGoal: 'Reframe prompting.',
    criticalTakeaway: 'Delegate structure, not soul.',
    skillWord: 'Structure',
    onScreenLine: 'Help me structure what I actually mean.',
    onScreenGloss: 'You keep intention; the model handles shape.',
  },
  {
    id: 'writing-06',
    timeRange: '7:08–7:38',
    segment: 'writing',
    slideLabel: 'Human core first',
    screenAction: 'Whiteboard or slide: three bullets.',
    script: 'First, write the human core yourself.\n\nUsually three bullets:\n\nwhat happened\nwhat I need\nwhat tone this should have\n\nExample: appreciated the meeting — need clarity on next step — answer by Friday.\n\nThat part is human. That part is the point.',
    teachingGoal: 'Teach core-first.',
    criticalTakeaway: 'Bullets carry stakes; AI should not invent those.',
  },
  {
    id: 'writing-07',
    timeRange: '7:38–8:06',
    segment: 'writing',
    slideLabel: 'Then AI for',
    screenAction: 'Live demo or recall prior chat.',
    script: 'Then I use AI for structure, shortening, tone adjustment, two or three variations.\n\n[pause]',
    teachingGoal: 'Teach division of labor.',
    criticalTakeaway: 'Prompting is scoped assistance.',
    skillWord: 'Prompting',
  },
  {
    id: 'writing-08',
    timeRange: '8:06–8:38',
    segment: 'writing',
    slideLabel: 'Put one human sentence back',
    screenAction: 'Highlight one line in output; edit live.',
    script: 'And then I do one more thing:\n\nput one human sentence back.\n\nOne sentence with actual life in it.\nOne sentence that sounds like I was there.\nOne sentence the machine would not invent unless it had my memory, my mood, and my exact stakes.',
    altJoke: 'Do not let the machine remove all evidence that you were here.',
    teachingGoal: 'Voice preservation rule.',
    criticalTakeaway: 'Leave fingerprints on the text.',
    skillWord: 'Voice',
  },
  {
    id: 'writing-09',
    timeRange: '8:38–9:30',
    segment: 'writing',
    slideLabel: 'Live contrast demo',
    screenAction: 'Bad prompt ("make this better") vs good prompt: task, tone, audience, constraints, anti-cliché.',
    script: 'Bad prompting is stress with punctuation.\n\nGood prompting names task, tone, audience, length, and what to avoid.\n\n[pause]',
    teachingGoal: 'Prompting basics live.',
    criticalTakeaway: 'Specificity reduces generic confidence.',
    skillWord: 'Prompting',
  },
  {
    id: 'writing-10',
    timeRange: '9:30–10:00',
    segment: 'writing',
    slideLabel: 'Segment 1 land',
    screenAction: 'Advance.',
    script: 'AI can help format your thought.\n\nDo not let it remove all evidence that you were here.\n\nThe danger is when efficiency starts replacing sincerity.',
    teachingGoal: 'Takeaway.',
    criticalTakeaway: 'Format help, keep sincerity.',
    skillWord: 'Tone',
    onScreenLine: 'Efficiency vs sincerity',
    onScreenGloss: 'Speed is a trade; do not pay with presence.',
  },
  {
    id: 'research-01',
    timeRange: '10:00–10:22',
    segment: 'research',
    slideLabel: 'Bridge',
    screenAction: 'Advance.',
    script: 'So okay — now maybe the email sounds human enough.\n\nUnfortunately, that does not mean we understand anything.\n\nWhich brings us to research.',
    teachingGoal: 'Bridge.',
    criticalTakeaway: 'Polish is not mastery.',
    skillWord: 'Summarization',
  },
  {
    id: 'research-02',
    timeRange: '10:22–10:46',
    segment: 'research',
    slideLabel: 'Research = survive the conversation',
    screenAction: 'Advance.',
    script: 'Research is really just a nicer word for:\n\n"I need to understand this fast enough to survive the conversation."\n\n[pause for laugh]',
    teachingGoal: 'Deflate pretense.',
    criticalTakeaway: 'Research is social survival.',
  },
  {
    id: 'research-03',
    timeRange: '10:46–11:12',
    segment: 'research',
    slideLabel: 'Summarize beautifully',
    screenAction: 'Optional: paste article opener into chat.',
    script: 'You have an article, a report, a deck, a transcript, a topic you were supposed to know about yesterday.\n\nSo you ask AI to summarize it.\n\nAnd it does.\n\nBeautifully.\n\nAlmost too beautifully.',
    teachingGoal: 'Setup seduction.',
    criticalTakeaway: 'Summaries feel like mastery.',
  },
  {
    id: 'research-04',
    timeRange: '11:12–11:38',
    segment: 'research',
    slideLabel: 'Emotional experience of knowledge',
    screenAction: 'Advance.',
    script: 'This is one of my favorite AI genres:\n\nthe emotional experience of knowledge.\n\n[pause for laugh]\n\nBecause now I have three bullet points, five takeaways, and a tone of confidence I did not earn.',
    altJoke: 'It gave me bullet points and my nervous system interpreted that as mastery.',
    teachingGoal: 'Name the genre.',
    criticalTakeaway: 'Feeling informed is not the same as knowing.',
    skillWord: 'Summarization',
  },
  {
    id: 'research-05',
    timeRange: '11:38–12:04',
    segment: 'research',
    slideLabel: 'Summary is not understanding',
    screenAction: 'Let line land.',
    script: 'A summary is not understanding.\n\nSometimes it is just confusion with better formatting.',
    teachingGoal: 'Core line + gloss.',
    criticalTakeaway: 'Separate summary from comprehension.',
    skillWord: 'Verification',
    onScreenLine: 'A summary is not understanding.',
    onScreenGloss: 'A summary is useful, but usefulness is not the same thing as ownership.',
  },
  {
    id: 'research-06',
    timeRange: '12:04–12:32',
    segment: 'research',
    slideLabel: 'Confidence is relational',
    screenAction: 'Advance.',
    script: 'Confidence is not nothing.\n\nConfidence is relational.\n\nYour boss wants to feel confident you can do the task.\nYou want to feel confident going into the presentation.\n\nBut now the machine can generate the tone, structure, and posture of confidence before you actually know.',
    teachingGoal: 'Synthetic confidence socially.',
    criticalTakeaway: 'Readiness can be manufactured.',
    skillWord: 'Confidence check',
  },
  {
    id: 'research-07',
    timeRange: '12:32–12:58',
    segment: 'research',
    slideLabel: 'Understand vs sound ready',
    screenAction: 'Advance.',
    script: 'So the question becomes:\n\ndo I understand this?\n\nor\n\ndo I just have a version of it that sounds ready?\n\n[pause]',
    teachingGoal: 'Binary for the room.',
    criticalTakeaway: 'Self-check before you speak.',
    skillWord: 'Confidence check',
  },
  {
    id: 'research-08',
    timeRange: '12:58–13:26',
    segment: 'research',
    slideLabel: 'Vibe-reading',
    screenAction: 'Advance.',
    script: 'This is where vibe-reading starts happening.\n\nSometimes we are no longer reading for truth.\n\nWe are reading for coherence, polish, smartness, presentability — whether this could survive a meeting.\n\nThat is vibe-reading.\n\nAnd it is dangerous.\n\nBecause vibe is not understanding.\nPolish is not proof.\nReadiness is not knowledge.',
    teachingGoal: 'Define vibe-reading.',
    criticalTakeaway: 'Friction: read for truth, not vibe.',
    skillWord: 'Friction',
  },
  {
    id: 'research-09',
    timeRange: '13:26–13:56',
    segment: 'research',
    slideLabel: 'Confidence check practice',
    screenAction: 'Type follow-up prompts in chat.',
    script: 'After any summary, ask yourself:\n\nWhat do I actually know here?\nWhat came from the model?\nWhat might be missing or oversimplified?\nWhat should I verify independently?\nWhat could I explain in my own words without looking?\n\n[pause]',
    teachingGoal: 'Teach confidence check.',
    criticalTakeaway: 'Verification is part of intelligence now.',
    skillWord: 'Verification',
  },
  {
    id: 'research-10',
    timeRange: '13:56–14:24',
    segment: 'research',
    slideLabel: 'Ask the machine its limits',
    screenAction: 'Type: what are you uncertain about? What is inferred?',
    script: 'Then ask the machine directly:\n\nWhat are you uncertain about?\nWhich parts are inferred rather than grounded?\nWhat would a skeptical reader question?\nWhat should not be trusted without checking?\n\n[pause]\n\nIf it cannot survive those questions, it was never knowledge.\n\nIt was formatting.',
    teachingGoal: 'Model-assisted friction.',
    criticalTakeaway: 'Interrogate outputs, not just read them.',
  },
  {
    id: 'research-11',
    timeRange: '14:24–14:52',
    segment: 'research',
    slideLabel: 'Hallucinations',
    screenAction: 'Advance.',
    script: 'Sometimes the answer is wrong — not cartoonishly wrong — just wrong in complete sentences.\n\n[pause for laugh]\n\nThat is what makes hallucinations dangerous.\n\nPlausible, smooth, organized, cite-shaped, emotionally calm.\n\nIt does not just make things up.\n\nIt makes things up in a tone that suggests you should not interrupt.',
    cultureBeat:
      'Optional: tie to AI-in-film debates — technically plausible surface long before it feels legitimate; smooth is not the same as true.',
    altJoke: 'It is not just wrong. It is wrong with excellent formatting.',
    teachingGoal: 'Hallucination tone.',
    criticalTakeaway: 'Plausibility is the trap.',
    skillWord: 'Verification',
  },
  {
    id: 'research-12',
    timeRange: '14:52–15:22',
    segment: 'research',
    slideLabel: 'Sycophancy',
    screenAction: 'Advance.',
    script: 'Then there is sycophancy — the machine agrees with you too easily.\n\nSometimes AI is not helping you think.\n\nIt is helping you continue.\n\n[pause]',
    teachingGoal: 'Name enabler dynamic.',
    criticalTakeaway: 'Support should not only ratify momentum.',
  },
  {
    id: 'research-13',
    timeRange: '15:22–15:52',
    segment: 'research',
    slideLabel: 'Anti-sycophancy prompt',
    screenAction: 'Type critique prompts live.',
    script: 'Ask:\n\nWhat is the strongest critique of this?\nWhat am I not seeing?\nArgue against my current assumption.\nWhat would a skeptical expert say?\nWhat are the failure modes?\n\n[pause]\n\nAI should not only support your momentum.\n\nIt should also interrupt your delusion.',
    teachingGoal: 'Teach anti-sycophancy.',
    criticalTakeaway: 'Prompt for resistance.',
    skillWord: 'Friction',
  },
  {
    id: 'research-14',
    timeRange: '15:52–16:22',
    segment: 'research',
    slideLabel: 'Continuity',
    screenAction: 'Advance.',
    script: 'Continuity is a superpower and a trap.\n\nThe machine can keep going — deeper, forever.\n\nAt some point you are not solving the problem anymore.\n\nYou are cultivating a relationship with the problem.\n\n[pause for laugh]',
    altJoke: 'At some point the thread is no longer helping you. It is using your afternoon.',
    teachingGoal: 'Continuity risk.',
    criticalTakeaway: 'Depth without exit becomes compulsion.',
  },
  {
    id: 'research-15',
    timeRange: '16:22–16:52',
    segment: 'research',
    slideLabel: 'Stopping rules',
    screenAction: 'Advance.',
    script: 'Before you start, decide:\n\nwhat counts as success?\nwhat counts as done?\nhow many rounds are enough?\nwhen do I stop prompting and move into a document?\nwhen do I ask another human?\n\n[pause]\n\nIf you do not define an exit, continuity can become compulsion.',
    teachingGoal: 'Stopping rules.',
    criticalTakeaway: 'Design exits before you prompt.',
    skillWord: 'Stopping rules',
  },
  {
    id: 'research-16',
    timeRange: '16:52–18:00',
    segment: 'research',
    slideLabel: 'Segment 2 recap + demo buffer',
    screenAction: 'Trim or extend live demo here if running long.',
    script: 'Principles:\n\nA summary is not understanding.\nConfidence is not comprehension.\nSometimes we are checking for the feeling of readiness, not truth.\nContinuity is the superpower and the trap.\n\n[pause]',
    teachingGoal: 'Land segment.',
    criticalTakeaway: 'Fluency, truth, comprehension: three different checks.',
    skillWord: 'Verification',
  },
  {
    id: 'brain-01',
    timeRange: '18:00–18:20',
    segment: 'brainstorming',
    slideLabel: 'Bridge',
    screenAction: 'Advance.',
    script: 'So now that we have looked at how AI can make us feel smarter than we are…\n\nlet us move to creativity, where it can also make us feel more imaginative than we are.',
    teachingGoal: 'Bridge.',
    criticalTakeaway: 'Creativity has its own seductions.',
    skillWord: 'Contrast',
  },
  {
    id: 'brain-02',
    timeRange: '18:20–18:42',
    segment: 'brainstorming',
    slideLabel: 'Spiritually suspicious',
    screenAction: 'Advance.',
    script: 'Brainstorming is where AI becomes both impressive and spiritually suspicious.\n\nYes — twenty ideas in ten seconds — and somehow that can still leave you feeling lonelier than before.\n\n[pause for laugh]',
    teachingGoal: 'Set paradox.',
    criticalTakeaway: 'Volume is not company.',
    skillWord: 'Selection',
  },
  {
    id: 'brain-03',
    timeRange: '18:42–19:08',
    segment: 'brainstorming',
    slideLabel: 'Future Now',
    screenAction: 'Optional live: "20 workshop titles…"',
    script: 'You ask for titles, concepts, names.\n\nThe machine says: "Absolutely. Here are 20 innovative ideas."\n\nAnd 17 of them sound like they were generated for a conference called Future Now.\n\n[pause for laugh]',
    altJoke: '20 ideas. 17 spiritually dead.',
    teachingGoal: 'Funny misuse.',
    criticalTakeaway: 'Default ideation is homogenized.',
  },
  {
    id: 'brain-04',
    timeRange: '19:08–19:34',
    segment: 'brainstorming',
    slideLabel: 'Autocomplete in a blazer',
    screenAction: 'Advance.',
    script: 'This is not imagination.\n\nThis is autocomplete wearing a blazer.\n\n[pause]\n\nOne thing AI is very good at is producing things usable enough to interrupt your patience, but not alive enough to replace your taste.',
    altJoke: 'This is not inspiration. This is content with excellent posture.',
    teachingGoal: 'Taste frame.',
    criticalTakeaway: 'Usable is not alive.',
    skillWord: 'Taste',
  },
  {
    id: 'brain-05',
    timeRange: '19:34–20:02',
    segment: 'brainstorming',
    slideLabel: 'Contrast prompt',
    screenAction: 'Type: 3 obvious, 3 strange, 3 wrong-but-interesting; avoid clichés.',
    script: 'Ask for three obvious, three strange, three wrong-but-interesting ideas.\n\nBetter prompting creates contrast, not just volume.\n\n[pause]',
    teachingGoal: 'Teach creative prompting.',
    criticalTakeaway: 'Contrast beats raw volume.',
    skillWord: 'Contrast',
  },
  {
    id: 'brain-06',
    timeRange: '20:02–20:32',
    segment: 'brainstorming',
    slideLabel: 'Sort: cliché / usable / alive',
    screenAction: 'Advance or live triage on screen.',
    script: 'Sort into cliché, usable, alive.\n\nMore options do not mean more imagination.\n\nAbundance is not discernment.',
    teachingGoal: 'Selection / triage.',
    criticalTakeaway: 'Taste is choosing what to refuse.',
    skillWord: 'Selection',
  },
  {
    id: 'brain-07',
    timeRange: '20:32–22:00',
    segment: 'brainstorming',
    slideLabel: 'Slop rot + land',
    screenAction: 'Advance.',
    script: 'Slop rot is what happens when repeated exposure to polished sameness lowers your standards slowly enough that you do not notice.\n\n[pause]\n\nThe danger is not that AI gives you no ideas.\n\nThe danger is that it gives you enough ideas to stop waiting for a better one.\n\n[pause]',
    cultureBeat:
      'Optional seasoning: something like Fruit Love Island shows how AI output can be obviously ridiculous and still socially magnetic — absurd, synthetic, sticky — a fair read on a lot of AI culture right now.',
    altJoke: 'It is not that the content is awful. It is that your nervous system starts allowing it.',
    teachingGoal: 'Close segment.',
    criticalTakeaway: 'Discernment erodes quietly.',
    skillWord: 'Discernment',
  },
  {
    id: 'synth-01',
    timeRange: '22:00–22:22',
    segment: 'synthetic_staff',
    slideLabel: 'Weird pivot',
    screenAction: 'Advance.',
    script: 'And now we get to the really weird one.\n\nThe point where AI stops feeling like a tool and starts feeling like a staff.',
    teachingGoal: 'Pivot.',
    criticalTakeaway: 'Stack changes how work feels.',
    skillWord: 'Assistant stack',
  },
  {
    id: 'synth-02',
    timeRange: '22:22–22:48',
    segment: 'synthetic_staff',
    slideLabel: 'Ten assistants',
    screenAction: 'List roles on slide.',
    script: 'Writing assistant, research assistant, planning assistant, note-taking assistant, brainstorming assistant, "please make me sound employable by 4 PM" assistant.\n\n[pause for laugh]\n\nThe fantasy is obvious: I can scale myself.',
    altJoke: 'Apparently I am now a manager. None of my employees are real.',
    teachingGoal: 'Name the stack fantasy.',
    criticalTakeaway: 'Synthetic scale is seductive.',
    skillWord: 'Assistant stack',
  },
  {
    id: 'synth-03',
    timeRange: '22:48–23:16',
    segment: 'synthetic_staff',
    slideLabel: 'Not the same as support',
    screenAction: 'Advance.',
    script: 'And to be fair: this is not fake.\n\nIt does help.\n\nBut here is where the story gets uncomfortable:\n\nhaving ten assistants is not the same as having support.\n\n[pause]',
    teachingGoal: 'Key line + gloss.',
    criticalTakeaway: 'Orchestration is still labor.',
    skillWord: 'Task boundaries',
    onScreenLine: '10 assistants ≠ support',
    onScreenGloss: 'Delegation can scale output and still leave you alone with the consequences.',
  },
  {
    id: 'synth-04',
    timeRange: '23:16–23:46',
    segment: 'synthetic_staff',
    slideLabel: 'Different labor',
    screenAction: 'Advance.',
    script: 'You still have to direct them, check them, revise them, hold the context, decide what matters, own the consequences.\n\nSo what you often gain is not less labor.\n\nIt is a different kind of labor — more supervision, orchestration, invisible management.',
    teachingGoal: 'Labor honesty.',
    criticalTakeaway: 'Support vs synthetic delegation.',
    skillWord: 'Oversight',
  },
  {
    id: 'synth-05',
    timeRange: '23:46–24:18',
    segment: 'synthetic_staff',
    slideLabel: 'Boss / you / AI loop',
    screenAction: 'Diagram or two-line slide.',
    script: 'With certain bosses — vague, not technical — I sometimes feel like the AI.\n\nThey delegate intention; I translate into execution.\n\nThen I open ChatGPT… and I become that same person.\n\n[pause]\n\nWith my boss, I feel like the AI.\nWith ChatGPT, I feel like the human.\n\nThat is the loop.\n\nAt work I am the machine. At home I am the manager. Somewhere in the middle, I am still supposed to be a person.\n\n[pause for laugh]',
    altJoke: 'My career path is just moving up and down the stack of delegated labor.',
    teachingGoal: 'Let anchor land.',
    criticalTakeaway: 'Role inversion is structural.',
    skillWord: 'Support',
  },
  {
    id: 'synth-06',
    timeRange: '24:18–24:48',
    segment: 'synthetic_staff',
    slideLabel: 'Recover the afternoon',
    screenAction: 'Advance.',
    script: 'My boss delegates to save time.\nI delegate to AI to save time.\n\nEverybody is just trying to recover an afternoon.\n\n[pause]',
    teachingGoal: 'Humanize.',
    criticalTakeaway: 'Delegation chains compress humanity.',
  },
  {
    id: 'synth-07',
    timeRange: '24:48–25:22',
    segment: 'synthetic_staff',
    slideLabel: 'Narrow helpers',
    screenAction: 'Advance.',
    script: 'Yes — use AI like narrow helpers: drafting, summarizing, organizing, comparing, brainstorming.\n\nBut do not confuse synthetic delegation with actual support.\n\nDo not confuse scale with stability.',
    teachingGoal: 'Practical boundary.',
    criticalTakeaway: 'Use assistants; demand real support too.',
    skillWord: 'Task boundaries',
  },
  {
    id: 'synth-08',
    timeRange: '25:22–25:52',
    segment: 'synthetic_staff',
    slideLabel: 'Justification risk',
    screenAction: 'Advance.',
    script: 'The question is not whether the assistants help you.\n\nThe question is whether they become the justification for why you no longer get actual assistance.\n\n[pause]',
    teachingGoal: 'Political edge.',
    criticalTakeaway: 'Tools can excuse withdrawal of care.',
    skillWord: 'Support',
  },
  {
    id: 'synth-09',
    timeRange: '25:52–27:00',
    segment: 'synthetic_staff',
    slideLabel: 'Scaling vs saving',
    screenAction: 'Advance.',
    script: 'Scaling yourself is not the same as saving yourself.\n\n[pause]\n\nAnd if you are going to work with these assistants repeatedly, we need to talk about shaping behavior, organizing context, and stopping them from quietly becoming your second job.',
    teachingGoal: 'Bridge to advanced systems.',
    criticalTakeaway: 'Next: infrastructure mindset.',
    skillWord: 'Task boundaries',
    onScreenLine: 'Scaling yourself is not the same as saving yourself.',
    onScreenGloss: 'Output can grow while relief does not.',
  },
  {
    id: 'adv-01',
    timeRange: '27:00–27:24',
    segment: 'advanced_systems',
    slideLabel: 'From one-off to setup',
    screenAction: 'Advance.',
    script: 'So far we have mostly talked about prompts like one-off requests.\n\nBut once the tools start helping enough, something else happens.\n\nYou stop asking: "How do I use AI for this one task?"\n\nAnd you start asking: "How do I set this up so it keeps helping me later?"\n\n[pause]\n\nThat is where AI stops feeling like a chatbot… and starts feeling like infrastructure.',
    teachingGoal: 'Infrastructure turn.',
    criticalTakeaway: 'Reliable help invites systems.',
    skillWord: 'Context',
  },
  {
    id: 'adv-02',
    timeRange: '27:24–27:52',
    segment: 'advanced_systems',
    slideLabel: 'System prompt',
    screenAction: 'Show example system prompt blocks.',
    script: 'A normal prompt is: help me do this.\n\nA system prompt is: here is who you are, how you should behave, what tone to use, what to avoid, what output I trust.\n\n[pause for laugh]\n\nBasically: a system prompt is the assistant personality lease agreement.\n\n[pause]',
    altJoke: 'Without a system prompt, the assistant is just spiritually freelancing.',
    teachingGoal: 'Teach system prompts.',
    criticalTakeaway: 'Language as behavior architecture.',
    skillWord: 'System prompt',
  },
  {
    id: 'adv-03',
    timeRange: '27:52–28:22',
    segment: 'advanced_systems',
    slideLabel: 'Power + caution',
    screenAction: 'Advance.',
    script: 'That is powerful — you are shaping behavior, not just output.\n\nBut it is also responsibility: you are designing defaults that will echo across every reply.',
    teachingGoal: 'Ethical beat.',
    criticalTakeaway: 'Defaults shape habits.',
    skillWord: 'System prompt',
  },
  {
    id: 'adv-04',
    timeRange: '28:22–28:52',
    segment: 'advanced_systems',
    slideLabel: 'Projects / memory / context',
    screenAction: 'UI tour or slide.',
    script: 'One chat is not enough.\n\nSome work has tone, history, stable preferences, recurring documents, unfinished parts, future versions.\n\nChats, projects, memory, files, context.\n\nOne chat is a task. A project is a container. Memory is for stable truths. Files are anchors.\n\n[pause for laugh]\n\nAt some point you are no longer using AI. You are managing an estate.\n\nMy interior life now has folders.',
    cultureBeat:
      'Optional: the “what ChatGPT thinks of me from my prompts” meme — one assistant soaking writing, summarizing, organizing, emotional formatting, existential cleanup; funny because it names the labor sponge.',
    altJoke: 'Apparently my thoughts now need onboarding documents.',
    teachingGoal: 'Containers.',
    criticalTakeaway: 'Context design beats clever one-offs.',
    skillWord: 'Context',
  },
  {
    id: 'adv-05',
    timeRange: '28:52–29:24',
    segment: 'advanced_systems',
    slideLabel: 'Scheduled prompts',
    screenAction: 'Examples on slide.',
    script: 'Scheduled prompts — weekly review, monthly planning, grant checks, what should I stop doing?, deadline prep.\n\nThe machine stops only answering… it starts showing up on time.\n\n[pause for laugh]\n\nThat can be genuinely helpful — sometimes people need better timing, not more intelligence.\n\nBut it also means the tool participates in your time, not just your language.',
    altJoke: 'Scheduled prompts are like having an assistant with excellent timing and no respect for your avoidance.',
    teachingGoal: 'Time-aware AI.',
    criticalTakeaway: 'Rhythm changes agency.',
    skillWord: 'Scheduled prompt',
  },
  {
    id: 'adv-06',
    timeRange: '29:24–29:56',
    segment: 'advanced_systems',
    slideLabel: 'Cloning / digital twin',
    screenAction: 'Advance.',
    script: 'Cloning yourself — tone, FAQs, style, recurring responses, project logic — can be useful.\n\nFeed examples, teach preferences, build a system prompt.\n\nBut there is a big difference between cloning the pattern and replacing the person.\n\n[pause]\n\nA digital twin is useful right up until it starts sounding more patient than you.\n\n[pause for laugh]',
    altJoke: 'Great, now there are two of me, and one of them is easier to work with.',
    teachingGoal: 'Clone ethics.',
    criticalTakeaway: 'Clone pattern, not judgment or accountability.',
    skillWord: 'Pattern cloning',
  },
  {
    id: 'adv-07',
    timeRange: '29:56–30:28',
    segment: 'advanced_systems',
    slideLabel: 'Clone the pattern',
    screenAction: 'Advance.',
    script: 'Clone formatting style, tone range, FAQ logic, structure, references.\n\nDo not pretend you cloned judgment, ethics, accountability, being there.',
    teachingGoal: 'Explicit boundaries.',
    criticalTakeaway: 'Pattern libraries are not conscience.',
    skillWord: 'Pattern cloning',
  },
  {
    id: 'adv-08',
    timeRange: '30:28–31:02',
    segment: 'advanced_systems',
    slideLabel: 'Airtable / n8n / artifacts',
    screenAction: 'Simple diagram if available.',
    script: 'AI joins other systems: Airtable, n8n, docs, forms, PDFs, automations.\n\nAirtable: structured memory.\nn8n: delegated repetition.\nAI in the middle: notes become summaries, one-pagers, decks, follow-ups.\n\n[pause for laugh]\n\nThe machine is very good at turning panic into artifacts.',
    altJoke: 'Airtable is what happens when your to-do list gets institutional ambitions.',
    teachingGoal: 'Stack literacy.',
    criticalTakeaway: 'Workflow thinking, not chat-only.',
    skillWord: 'Automation',
  },
  {
    id: 'adv-09',
    timeRange: '31:02–31:36',
    segment: 'advanced_systems',
    slideLabel: 'Automation trade',
    screenAction: 'Advance.',
    script: 'Automation solves repetition and creates maintenance.\n\n[pause]\n\nYou wanted freedom. Now you have workflows, triggers, exceptions, prompt upkeep, syncing problems — systems for the systems that were supposed to help.',
    teachingGoal: 'Quote + gloss.',
    criticalTakeaway: 'Budget upkeep tax.',
    skillWord: 'Automation',
    onScreenLine: 'Automation solves repetition and creates maintenance.',
    onScreenGloss: 'The work does not disappear. It changes shape.',
    transitionToNext:
      'So even when the work doesn’t disappear, something else does shift:\n\nthe system starts taking over not only pieces of the task,\nbut pieces of our relationship to the task.\n\n[pause]\n\nAnd that’s where I want to introduce one more concept:\n\ninterpassivity.',
    deckSlideNumber: 45,
  },
  {
    id: 'adv-interpassivity',
    timeRange: '31:36–32:18',
    segment: 'interpassivity',
    slideLabel: 'Interpassivity',
    screenAction: 'Advance. Deck v2: slide 46.',
    script:
      'And I think there’s one more layer here that matters.\n\nNot just automation.\nNot just assistance.\nNot just speed.\n\nBut interpassivity.\n\nWhich is when the system starts performing the response for you.\n\nIt remembers for you.\nIt reacts for you.\nIt drafts for you.\nIt organizes for you.\nIt creates the feeling that the thing has already been handled.\n\n[pause]\n\nAnd that can feel incredible.\n\nBecause some part of your burden really does get lifted.\n\nBut it also creates a strange question:\n\nif the machine is increasingly doing the remembering, sorting, drafting, and even first-round feeling for me…\n\nwhat part of the process am I still actually inhabiting?\n\n[pause]\n\nThis is not me saying that help is bad.\n\nIt’s me saying that relief has a psychology.\n\nSometimes the system doesn’t just help me do the task.\n\nIt helps me feel like the task has already passed through me.',
    altJoke:
      'Interpassivity is when the machine doesn’t just do the homework — it also raises its hand with the confidence I was hoping to borrow.',
    teachingGoal: 'Name outsourced “response” and relief psychology.',
    criticalTakeaway:
      'AI can outsource not only labor, but the sense that labor has already been metabolized.',
    skillWord: 'Interpassivity',
    onScreenLine: 'Interpassivity',
    onScreenGloss:
      'When the system performs the response for you.\n\n• it remembers for me\n• it reacts for me\n• it drafts for me\n• it organizes for me\n• it “dealt with it” for me',
    slideVisualPurpose:
      'Name the deeper move after automation: the machine doesn’t only do tasks — it can perform remembering, reacting, and “handled-ness” on your behalf.',
    slideImagePromptDark:
      'Calm organized interface completing emotional and administrative responses on behalf of a human who is physically present but slightly displaced, dark editorial, cinematic realism, subtle interface overlays, premium presentation slide aesthetic, subtle surrealism, not stock photo, no obvious robots',
    slideImagePromptLight:
      'Calm organized interface completing emotional and administrative responses on behalf of a human who is physically present but slightly displaced, light background, subtle surrealism, editorial conceptual realism, system performing response for the user, premium presentation aesthetic, not stock photo',
    transitionToNext:
      'That layer — when relief can feel like the task already passed through you — sits on top of everything else automation asks of you next.',
    deckSlideNumber: 46,
    notes:
      'Deck v2: insert as slide 46 after automation. If your deck goes straight from Interpassivity to What Should Stay Human (no Part-time job / Environment / buffer slides), move the long bridge currently on adv-12 to the end of this beat and jump to wsh-01.',
  },
  {
    id: 'adv-10',
    timeRange: '32:18–32:50',
    segment: 'advanced_systems',
    slideLabel: 'Part-time job',
    screenAction: 'Advance.',
    script: 'You automate your life… and managing the automation becomes a part-time job.\n\n[pause]',
    altJoke: 'I automated the task and inherited the governance.',
    teachingGoal: 'Land contradiction.',
    criticalTakeaway: 'Governance follows automation.',
  },
  {
    id: 'adv-11',
    timeRange: '32:50–33:24',
    segment: 'advanced_systems',
    slideLabel: 'Environment',
    screenAction: 'Advance.',
    script: 'Be careful when help becomes infrastructure.\n\nOnce the tool is recurring, scheduled, behavioral, cloned, automated — it stops being only convenience.\n\nIt becomes part of the environment shaping how you work, remember, write, decide, and organize your life.',
    teachingGoal: 'Stakes.',
    criticalTakeaway: 'Infrastructure shapes identity over time.',
    skillWord: 'Context',
  },
  {
    id: 'adv-12',
    timeRange: '33:24–34:42',
    segment: 'advanced_systems',
    slideLabel: 'Buffer / tighten',
    screenAction: 'Trim or deepen Airtable/n8n demo here.',
    script:
      'So yes: use prompts, shape the assistant, schedule check-ins, build workflows, generate artifacts — but stay awake to what you are building around yourself.\n\n[pause]\n\nIf you need to trim for time, this is where you cut or deepen the stack demo.',
    teachingGoal: 'Bridge to values.',
    criticalTakeaway: 'Next: what stays human?',
    transitionToNext:
      'So after all the prompts, the systems, the automations, the scheduling, the memory, and now even the outsourced response…\n\n[pause]\n\nthe most important question becomes very simple:\n\nwhat should still belong to a person?',
  },
  {
    id: 'wsh-01',
    timeRange: '34:42–35:22',
    segment: 'what_stays_human',
    slideLabel: 'The question',
    screenAction: 'Advance.',
    script: 'What should stay human?\n\n[pause]',
    teachingGoal: 'Moral re-anchor.',
    criticalTakeaway: 'Delegate tasks, not conscience.',
    skillWord: 'Judgment',
    deckSlideNumber: 47,
  },
  {
    id: 'wsh-02',
    timeRange: '35:22–36:06',
    segment: 'what_stays_human',
    slideLabel: 'Split the work',
    screenAction: 'Advance.',
    script: 'AI can help with drafts, summaries, formatting, comparisons, repetition, speed.\n\nBut some things should remain yours:\n\nintention, judgment, taste, ethics, context, emotional truth, final choice.\n\n[pause]',
    teachingGoal: 'Explicit list.',
    criticalTakeaway: 'Keep final choice human.',
    skillWord: 'Final choice',
  },
  {
    id: 'wsh-03',
    timeRange: '36:06–37:42',
    segment: 'what_stays_human',
    slideLabel: 'What not to automate',
    screenAction: 'Advance.',
    script: 'The problem is not automation by itself.\n\nThe problem begins when we automate the parts of ourselves that matter most.\n\n[pause]\n\nThe tools can help you work faster.\n\nThat does not mean they should decide what matters, what sounds right, what gets believed, what gets kept, or who you become while using them.',
    teachingGoal: 'Ethical guardrail.',
    criticalTakeaway: 'Speed is not a license to outsource meaning.',
    skillWord: 'Taste',
  },
  {
    id: 'close-01',
    timeRange: '37:42–38:27',
    segment: 'closing',
    slideLabel: 'Not purity',
    screenAction: 'Advance.',
    script: 'So the point of this workshop is not purity.\n\nMost of us are going to use these tools. I use them.\n\nThe point is not to reject assistance.\n\nThe point is to stay awake inside it.\n\n[pause]',
    teachingGoal: 'Permission structure.',
    criticalTakeaway: 'Assistance yes; sleepwalking no.',
  },
  {
    id: 'close-02',
    timeRange: '38:27–39:17',
    segment: 'closing',
    slideLabel: 'Principles stack',
    screenAction: 'Build bullets on slide.',
    script: 'Use AI for assistance, not surrender.\n\nA summary is not understanding.\nMore options do not mean more imagination.\nScaling yourself is not the same as saving yourself.\n\n[pause]',
    teachingGoal: 'Compress principles.',
    criticalTakeaway: 'Repeatable closing lines.',
    skillWord: 'Judgment',
    onScreenLine: 'Use AI for assistance, not surrender.',
    onScreenGloss: 'Let the machine help with labor, not with who you become.',
    deckSlideNumber: 48,
  },
  {
    id: 'close-03',
    timeRange: '39:17–40:12',
    segment: 'closing',
    slideLabel: 'Evidence you were here',
    screenAction: 'Final slide.',
    script: 'And maybe most importantly:\n\ndo not let the machine remove all evidence that you were here.\n\n[pause]\n\nThank you.',
    altJoke: 'The goal is not to stay pure. The goal is to stay recognizable to yourself.',
    teachingGoal: 'Final line.',
    criticalTakeaway: 'Presence over polish.',
    skillWord: 'Final choice',
    deckSlideNumber: 49,
  },
  {
    id: 'close-04',
    timeRange: '40:12–40:42',
    segment: 'closing',
    slideLabel: 'Hold / applause',
    screenAction: 'Hold. Bow if that is your thing.',
    script: '',
    teachingGoal: 'Room.',
    criticalTakeaway: '—',
  },
  {
    id: 'flex-01',
    timeRange: '—',
    segment: 'flex',
    slideLabel: 'Flex / stretch',
    screenAction: 'If running long 40-minute version: stretch Seg 2 (+2), Seg 4 (+2), advanced (+1–2), closing reflection (+1).',
    script: '',
    teachingGoal: 'Budget padding for live room.',
    criticalTakeaway: 'Trim segments for shorter formats; keep opening + formula + two deep segments + closing.',
    notes: 'Bridge lines between segments: sound professional → know anything; feel informed → still have taste; generate ideas → tool as team; team exists → help as infrastructure. v2: after automation, interpassivity names outsourced “response”; then land Part-time job / Environment / buffer before What Stays Human unless using a compact deck.',
  },
]
