// Master list of mid-tail SEO keywords for Moises Sanabria's site
// Update quarterly as trends shift

const rawKeywords = [
  'ai art',
  'generative ai art',
  'machine learning art',
  'ai sculpture',
  'interactive installation art',
  'computer vision art',
  'algorithmic art',
  'virtual reality art',
  'vr performance art',
  'cybernetic aesthetics',
  'post-internet sculpture',
  'accelerationism',
  'memetics',
  'machine philosophy',
  'surveillance art',
  'privacy sculpture',
  'technofetishism',
  'doomscrolling',
  'brain rot meme',
  'attention economy art',
  'capitalism critique art',
  'data capitalism',
  'digital capitalism',
  'consumerism art',
  'nft conceptual art',
  'google gradients',
  'cuteveillance',
  'moises sanabria artist',
  'creative ai',
  'miami artist',
  'new media art',
  'new media artwork',
  'brain rot content',
  'doomscrolling art',
  'the art of doomscrolling',
  'contemporary art miami',
  'ai art contemporary',
  'ai sculpting',
  'moises meme art',
  'moises machine philosophy',
  'machine philosophy near me',
  'the art of memetics',
  'memetic art',
  'materializing new media',
  'material internet',
  'synthetic media',
  'post-internet sculpture',
  'brain rot sculpture',
  'tech art that critiques capitalism',
  'interactive internet art',
  'technoromanticism',
  'art technology and attention',
  'data center sculpture',
  'virtual headset art',
  'tech readymade',
  'low-effort contemporary art',
  'bolivares skeleton art',
  'gan art',
  'virtual reality hug art',
  'accelerationism art',
  'memetics art',
  'privacy sculpture',
  'data center sculpture',
  'data capitalism',
  'digital capitalism',
  'consumerism art',
];

// Deduplicate, lower-case, and trim
const uniqueKeywords = Array.from(new Set(rawKeywords.map(k => k.toLowerCase().trim())));

// Alphabetical sort
export const seoKeywordsAlpha = [...uniqueKeywords].sort();

// Sort by phrase length (shortest to longest)
export const seoKeywordsByLength = [...uniqueKeywords].sort((a, b) => a.length - b.length); 