'use client';

import { AuthorshipType, AIDisplayMode } from '@/lib/book/types';
import { Info } from 'lucide-react';
import { useState } from 'react';

interface AuthorshipBadgeProps {
  type: AuthorshipType;
  displayMode?: AIDisplayMode;
  showTooltip?: boolean;
  className?: string;
}

const BADGE_CONFIG = {
  human: {
    icon: '●',
    label: 'Human',
    description: 'Written fully by the author, untouched by AI',
    subtle: 'text-blue-600 border-blue-200',
    prominent: 'bg-blue-50 text-blue-700 border-blue-300 font-semibold',
  },
  hybrid: {
    icon: '◐',
    label: 'Hybrid',
    description: 'Co-written, where AI suggested or reshaped text in response to the author',
    subtle: 'text-purple-600 border-purple-200',
    prominent: 'bg-purple-50 text-purple-700 border-purple-300 font-semibold',
  },
  ai: {
    icon: '○',
    label: 'AI Draft',
    description: 'Text primarily generated by AI as a starting point, to be heavily edited or challenged',
    subtle: 'text-orange-600 dark:text-orange-400 border-orange-300 dark:border-orange-600',
    prominent: 'bg-orange-100 dark:bg-orange-900/40 text-orange-800 dark:text-orange-200 border-orange-400 dark:border-orange-600 font-semibold',
  },
  notes: {
    icon: '•',
    label: 'Notes',
    description: 'General notes, observations, or thoughts',
    subtle: 'text-green-600 border-green-200',
    prominent: 'bg-green-50 text-green-700 border-green-300 font-semibold',
  },
  authors: {
    icon: '@',
    label: 'Authors',
    description: 'References to authors, thinkers, or sources',
    subtle: 'text-red-600 border-red-200',
    prominent: 'bg-red-50 text-red-700 border-red-300 font-semibold',
  },
  vocabulary: {
    icon: '§',
    label: 'Vocabulary',
    description: 'Key terms, definitions, or vocabulary words',
    subtle: 'text-cyan-600 border-cyan-200',
    prominent: 'bg-cyan-50 text-cyan-700 border-cyan-300 font-semibold',
  },
};

export function AuthorshipBadge({
  type,
  displayMode = 'subtle',
  showTooltip = true,
  className = '',
}: AuthorshipBadgeProps) {
  const [showTooltipState, setShowTooltipState] = useState(false);
  const config = BADGE_CONFIG[type];
  const isProminent = displayMode === 'prominent';

  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs border ${
        isProminent ? config.prominent : config.subtle
      } ${className}`}
      onMouseEnter={() => showTooltip && setShowTooltipState(true)}
      onMouseLeave={() => setShowTooltipState(false)}
    >
      <span className="text-sm">{config.icon}</span>
      {isProminent && <span>{config.label}</span>}
      {showTooltip && showTooltipState && (
        <div className="absolute z-50 mt-6 ml-0 p-2 bg-gray-900 text-white text-xs rounded shadow-lg max-w-xs">
          <div className="font-semibold mb-1">{config.label}</div>
          <div>{config.description}</div>
        </div>
      )}
    </span>
  );
}
